openapi: 3.0.0
info:
  title: "Example Connexion REST API"
  description: "A simple demo connexion API"
  version: "0.1.0"
# Can I do /api/{version}?
servers:
  - url: "/api"

paths:
  /users:
    get:
      operationId: "users.get_all"
      tags:
        - "Users"
      summary: "Read the list of users"
      responses:
        "200":
          description: "Successfully read all users"
